In [6]:
# Data was exported from R so it can be used in python

# Load and Inspect Data in python

import pandas as pd

df = pd.read_csv("classifier_input.csv", index_col = 0)
print(df.shape)
df.head()

(12, 31)

,MT4,CTHRC1,CD163,CD300E,CST6,IGFL2,GSTO1,COL4A1,SERPINE1,SERPINB7,...,CD276,COL4A2,TOB2,ARHGEF26,LTF,PSAPL1,EIF4EBP1,PI15,PER2,condition
donor1_lesional,6.125105,8.229915,6.720274,6.650569,8.624690,5.799774,10.782634,8.600247,8.395316,5.923145,...,8.402402,8.261433,10.534351,7.661204,9.954703,4.597461,10.089223,7.053035,8.695626,lesional
donor1_nonlesional,9.298202,6.400012,5.057577,4.998058,9.441933,8.432811,10.026204,7.166627,7.308127,8.592244,...,7.344425,6.816526,11.060483,8.694212,7.996533,7.425730,9.182659,4.100259,9.761210,nonlesional
donor2_lesional,4.057701,9.595600,7.027818,6.568600,8.307901,5.583720,10.668422,10.014147,9.800563,4.481870,...,7.941073,9.707868,10.095207,7.412238,9.066208,3.787318,9.608806,7.855020,8.967138,lesional
donor2_nonlesional,7.659820,8.667997,4.590448,4.590448,10.580854,7.636092,10.080816,9.099603,8.725344,7.815811,...,7.191268,8.440336,10.880044,8.169893,7.374508,6.383176,8.714055,6.594914,9.757022,nonlesional
donor3_lesional,2.552301,10.443553,9.179952,8.331524,7.970233,5.680291,11.356444,10.799155,10.393983,4.991683,...,9.321990,10.387010,9.523012,6.041679,9.183981,4.354929,10.289423,9.250799,7.922808,lesional

In [7]:
# Separate features from the label

x = df.drop(columns= ["condition"])
y = df["condition"]

print(x.shape)
y.value_counts()

(12, 30)

condition
lesional       6
nonlesional    6
Name: count, dtype: int64

In [10]:
# Setup Leave-One-Out-Cross-Validation with logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import LeaveOneOut, cross_val_score

leoo = LeaveOneOut()
model = LogisticRegression(max_iter = 1000)

scores = cross_val_score(model, x, y, cv = leoo)
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# Load the full expression data

df_full = pd.read_csv("classifier_input_full.csv", index_col=0)
df_full.shape

(12, 29391)

In [13]:
# Separate features and labels again

x_full = df_full.drop(columns = ["condition"])
y_full = df_full["condition"]

print(x_full.shape)
print(y_full.value_counts())

(12, 29390)
condition
lesional       6
nonlesional    6
Name: count, dtype: int64

In [14]:
# Build a leak-free pipeline

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("feature_selection", SelectKBest(score_func = f_classif, k=30)),
    ("classifier", LogisticRegression(max_iter = 1000))
])

scores_full = cross_val_score(pipeline, x_full, y_full, cv = leoo)
scores_full

C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:110: UserWarning: Features [    2    93   229   230   308   309   384   555   674   771   895   952
   983  1150  1239  1270  1362  1399  1896  1919  2223  2514  2527  2741
  3043  3097  3330  3332  3478  3481  3881  3895  3986  3987  3990  4035
  4103  4154  4155  4488  4677  4865  4990  5031  5042  5083  5175  5208
  5226  5300  5376  5553  5618  5627  5699  5710  5744  5908  6003  6147
  6149  6218  6219  6349  6352  6394  6403  6428  6548  6556  6865  6894
  6955  6964  7124  7141  7311  7325  7386  7509  7520  8075  8106  8109
  8138  8174  8622  8631  8633  8637  9062  9096  9187  9276  9456  9534
  9794  9840  9904  9954  9967 10069 10073 10283 10393 10454 10463 10518
 10576 10602 10621 10623 10729 10939 10984 10994 11010 11089 11193 11339
 11462 11551 11707 11716 11930 11934 12445 12542 12649 12946 12992 13273
 13326 13327 13331 13332 13438 13485 13499 13633 13643 13676 13687 13708
 14086 14527 14635 14638 14773 14834 14867 14975 15108 15449 15690 15694
 15851 15896 15954 16171 16199 16273 16322 16330 16349 16454 16508 16514
 16559 16597 16757 16936 16995 17154 17161 17281 17292 17495 17501 17759
 17786 17791 17925 18127 18244 18289 18398 18481 18594 18597 18599 18742
 18968 19014 19406 19473 19561 19644 19692 19791 19850 19851 19859 19936
 19961 20096 20397 20470 20586 20637 20648 20680 20689 20706 20717 20727
 20746 20933 21008 21009 21176 21220 21546 21568 21609 21779 21866 21933
 21992 22386 22574 22659 22721 22920 23004 23386 23485 23845 23853 23912
 23916 23948 23960 23997 24058 24089 24116 24176 24282 24284 24294 24336
 24337 24364 24368 24392 24394 24399 24409 24418 24422 24455 24504 24518
 24578 24603 24639 24660 24686 24687 24690 24704 24744 24780 24812 24892
 24931 24932 24938 24951 24996 25007 25030 25042 25044 25051 25068 25070
 25083 25086 25088 25100 25107 25142 25147 25150 25159 25162 25172 25201
 25236 25242 25245 25269 25282 25294 25297 25319 25321 25324 25336 25337
 25338 25343 25362 25367 25371 25377 25389 25397 25427 25438 25441 25461
 25467 25468 25472 25495 25502 25503 25525 25549 25567 25595 25601 25612
 25633 25634 25635 25649 25669 25680 25685 25692 25709 25722 25728 25750
 25768 25772 25773 25775 25786 25806 25808 25819 25821 25823 25833 25841
 25846 25872 25878 25884 25891 25916 25920 25921 25943 25959 25971 25979
 26001 26010 26115 26392 26558 26917 26963 27033 27045 27115 27117 27120
 27146 27169 27171 27173 27183 27187 27190 27195 27203 27212 27221 27222
 27228 27240 27259 27263 27275 27287 27292 27308 27349 27351 27358 27360
 27391 27393 27396 27415 27421 27440 27443 27458 27469 27478 27484 27488
 27515 27517 27530 27540 27547 27548 27550 27591 27599 27617 27637 27638
 27642 27644 27647 27655 27659 27660 27664 27677 27680 27682 27683 27692
 27730 27745 27764 27766 27775 27779 27786 27787 27791 27797 27801 27802
 27808 27818 27821 27827 27831 27832 27844 27845 27847 27851 27863 27868
 27869 27873 27895 27899 27907 27910 27913 27915 27918 27924 27929 27944
 27951 27953 27954 27959 27974 27976 27978 27979 28005 28007 28009 28023
 28026 28028 28029 28032 28036 28068 28089 28090 28093 28099 28102 28112
 28115 28125 28126 28130 28147 28149 28157 28164 28167 28168 28171 28172
 28174 28179 28182 28190 28199 28221 28232 28235 28238 28276 28291 28293
 28294 28300 28309 28311 28316 28317 28319 28321 28329 28370 28373 28388
 28391 28392 28398 28399 28409 28414 28416 28426 28431 28433 28436 28443
 28445 28470 28484 28489 28493 28494 28515 28518 28519 28520 28533 28547
 28573 28595 28603 28627 28631 28632 28650 28655 28662 28668 28689 28713
 28751 28781 28788 28814 28840 28841 28842 28858 28864 28872 28885 28892
 28907 28910 28926 28930 28934 28937 28938 28943 28944 28950 28956 28960
 28969 28971 28978 28979 28987 28989 28993 28997 28999 29005 29012 29017
 29020 29023 29024 29032 29033 29037 29042 29049 29052 29063 29078 29080
 29087 29091 29102 29106 29115 29116 29119 29120 29126 29131 29141 29143
 29146 29150 29156 29161 29168 29173 29176 29178 29180 29181 29182 29183
 29185 29197 29198 29207 29208 29216 29225 29232 29236 29237 29239 29245
 29246 29257 29258 29262 29266 29267 29268 29270 29274 29286 29288 29289
 29296 29299 29308 29309 29310 29314 29324 29325 29328 29329 29333 29334
 29335 29337 29341 29347 29355 29360 29362 29364 29366 29368 29372 29376
 29378 29380 29381 29383 29385 29389] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:110: UserWarning: Features [   93   229   230   308   309   384   555   674   895   952   983  1001
  1017  1150  1239  1270  1362  1399  1896  1919  2223  2527  2991  3097
  3098  3101  3251  3330  3332  3478  3803  3822  3881  3895  3987  3990
  4035  4103  4154  4155  4488  4677  4865  4990  5031  5042  5208  5226
  5300  5376  5627  5699  5710  5744  6003  6147  6149  6219  6349  6352
  6394  6403  6428  6510  6548  6556  6574  6865  6894  6955  6964  7091
  7141  7309  7311  7325  7386  7509  7520  8075  8106  8138  8174  8631
  8633  8637  8729  9062  9096  9187  9276  9456  9534  9627  9651  9794
  9840  9904  9954 10069 10073 10146 10283 10393 10463 10576 10602 10623
 10939 10984 11010 11193 11392 11551 11699 11707 11716 11930 11934 12244
 12542 12586 12649 12810 12894 12946 12992 13273 13326 13327 13438 13468
 13499 13633 13643 13676 13687 13708 13817 13865 14527 14773 14834 14867
 15108 15690 15694 15851 15896 15935 15954 16052 16171 16199 16273 16322
 16454 16514 16559 16597 16936 16995 17161 17281 17287 17292 17495 17790
 17925 17961 18127 18244 18296 18318 18398 18481 18594 18599 18742 18968
 19014 19406 19473 19549 19692 19791 19859 19936 19961 20346 20397 20470
 20586 20603 20637 20648 20680 20689 20717 20746 20996 21009 21176 21228
 21546 21568 21609 21736 21866 21933 22386 22416 22574 22709 22721 22920
 22922 23012 23349 23386 23853 23912 23916 23960 23997 24058 24116 24176
 24282 24284 24294 24336 24337 24364 24368 24392 24394 24399 24409 24418
 24422 24455 24504 24518 24578 24603 24639 24660 24686 24687 24690 24704
 24744 24780 24812 24892 24931 24932 24938 24951 24996 25007 25030 25042
 25044 25051 25068 25070 25083 25086 25088 25100 25107 25142 25147 25150
 25159 25162 25172 25201 25236 25242 25245 25269 25282 25294 25297 25319
 25321 25324 25336 25337 25338 25343 25362 25367 25371 25377 25389 25397
 25427 25438 25441 25461 25467 25468 25472 25495 25502 25503 25525 25549
 25567 25595 25601 25612 25633 25634 25635 25649 25669 25680 25685 25692
 25709 25722 25728 25750 25768 25772 25773 25775 25786 25806 25808 25819
 25821 25823 25833 25841 25846 25872 25878 25884 25891 25916 25920 25921
 25943 25959 25971 25979 26001 26010 26115 26392 26558 26917 26963 27033
 27045 27115 27117 27120 27146 27169 27171 27173 27183 27187 27190 27195
 27203 27212 27221 27222 27228 27240 27259 27263 27275 27287 27292 27308
 27349 27351 27358 27360 27391 27393 27396 27415 27421 27440 27443 27458
 27469 27478 27484 27488 27515 27517 27530 27540 27547 27548 27550 27591
 27599 27617 27637 27638 27642 27644 27647 27655 27659 27660 27664 27677
 27680 27682 27683 27692 27730 27745 27764 27766 27775 27779 27786 27787
 27791 27797 27801 27802 27808 27818 27821 27827 27831 27832 27844 27845
 27847 27851 27863 27868 27869 27873 27895 27899 27907 27910 27913 27915
 27918 27924 27929 27944 27951 27953 27954 27959 27974 27976 27978 27979
 28005 28007 28009 28023 28026 28028 28029 28032 28036 28068 28089 28090
 28093 28099 28102 28112 28115 28125 28126 28130 28147 28149 28157 28164
 28167 28168 28171 28172 28174 28179 28182 28190 28199 28221 28232 28235
 28238 28276 28291 28293 28294 28300 28309 28311 28316 28317 28319 28321
 28329 28370 28373 28388 28391 28392 28398 28399 28409 28414 28416 28426
 28431 28433 28436 28443 28445 28470 28484 28489 28493 28494 28515 28518
 28519 28520 28533 28547 28573 28595 28603 28627 28631 28632 28650 28655
 28662 28668 28689 28713 28751 28781 28788 28814 28840 28841 28842 28858
 28864 28872 28885 28892 28907 28910 28926 28930 28934 28937 28938 28943
 28944 28950 28956 28960 28969 28971 28978 28979 28987 28989 28993 28997
 28999 29005 29012 29017 29020 29023 29024 29032 29033 29037 29042 29049
 29052 29063 29078 29080 29087 29091 29102 29106 29115 29116 29119 29120
 29126 29131 29141 29143 29146 29150 29156 29161 29168 29173 29176 29178
 29180 29181 29182 29183 29185 29197 29198 29207 29208 29216 29225 29232
 29236 29237 29239 29245 29246 29257 29258 29262 29266 29267 29268 29270
 29274 29286 29288 29289 29296 29299 29308 29309 29310 29314 29324 29325
 29328 29329 29333 29334 29335 29337 29341 29347 29355 29360 29362 29364
 29366 29368 29372 29376 29378 29380 29381 29383 29385 29389] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:110: UserWarning: Features [   93   229   230   308   309   384   555   674   895   952   983  1150
  1239  1270  1324  1362  1399  1896  1919  2223  2527  3097  3330  3332
  3478  3881  3895  3987  3990  4035  4103  4154  4155  4488  4677  4865
  4990  5031  5042  5208  5226  5300  5376  5627  5699  5710  5744  6003
  6048  6147  6149  6219  6349  6352  6394  6403  6428  6548  6556  6573
  6865  6894  6955  6964  7141  7311  7325  7386  7509  7511  7520  8075
  8106  8138  8174  8631  8633  8637  9062  9096  9187  9276  9456  9534
  9794  9840  9904  9954 10069 10073 10283 10393 10463 10576 10602 10623
 10939 10984 11010 11193 11551 11707 11716 11930 11934 12542 12649 12946
 12992 13273 13326 13327 13438 13499 13633 13643 13676 13687 13708 14527
 14760 14773 14834 14867 15108 15690 15694 15851 15896 15954 16171 16199
 16258 16273 16322 16454 16514 16559 16597 16936 16995 17161 17185 17281
 17292 17495 17925 18127 18244 18398 18481 18594 18599 18742 18968 19014
 19406 19473 19692 19791 19859 19936 19961 20397 20470 20586 20637 20648
 20680 20689 20717 20746 21009 21176 21546 21568 21609 21866 21933 22386
 22574 22721 22920 23017 23386 23853 23912 23916 23960 23997 24006 24036
 24058 24116 24176 24261 24262 24265 24280 24282 24284 24294 24301 24321
 24329 24336 24337 24352 24364 24368 24392 24394 24399 24409 24418 24422
 24425 24441 24450 24455 24504 24518 24519 24578 24603 24635 24639 24640
 24656 24660 24686 24687 24690 24698 24704 24705 24712 24720 24744 24745
 24780 24803 24812 24818 24846 24859 24878 24892 24895 24931 24932 24938
 24951 24954 24956 24963 24967 24973 24993 24996 25007 25029 25030 25033
 25034 25042 25044 25051 25066 25068 25070 25083 25086 25088 25100 25104
 25107 25110 25113 25140 25142 25147 25150 25159 25162 25172 25178 25194
 25201 25204 25207 25216 25230 25236 25242 25245 25266 25269 25282 25294
 25297 25310 25319 25321 25324 25336 25337 25338 25343 25362 25367 25371
 25377 25389 25397 25427 25438 25441 25461 25467 25468 25472 25495 25502
 25503 25525 25549 25567 25595 25601 25612 25633 25634 25635 25649 25669
 25680 25685 25692 25709 25722 25728 25750 25768 25772 25773 25775 25786
 25806 25808 25819 25821 25823 25833 25841 25846 25872 25878 25884 25891
 25916 25920 25921 25943 25959 25971 25979 26001 26010 26115 26392 26558
 26917 26963 27033 27045 27115 27117 27120 27146 27169 27171 27173 27183
 27187 27190 27195 27203 27212 27221 27222 27228 27240 27259 27263 27275
 27287 27292 27308 27349 27351 27358 27360 27391 27393 27396 27415 27421
 27440 27443 27458 27469 27478 27484 27488 27515 27517 27530 27540 27547
 27548 27550 27591 27599 27617 27637 27638 27642 27644 27647 27655 27659
 27660 27664 27677 27680 27682 27683 27692 27730 27745 27764 27766 27775
 27779 27786 27787 27791 27797 27801 27802 27808 27818 27821 27827 27831
 27832 27844 27845 27847 27851 27863 27868 27869 27873 27895 27899 27907
 27910 27913 27915 27918 27924 27929 27944 27951 27953 27954 27959 27974
 27976 27978 27979 28005 28007 28009 28023 28026 28028 28029 28032 28036
 28068 28089 28090 28093 28099 28102 28112 28115 28125 28126 28130 28147
 28149 28157 28164 28167 28168 28171 28172 28174 28179 28182 28190 28199
 28221 28232 28235 28238 28276 28291 28293 28294 28300 28309 28311 28316
 28317 28319 28321 28329 28370 28373 28388 28391 28392 28398 28399 28409
 28414 28416 28426 28431 28433 28436 28443 28445 28470 28484 28489 28493
 28494 28515 28518 28519 28520 28533 28547 28573 28595 28603 28627 28631
 28632 28650 28655 28662 28668 28689 28713 28751 28781 28788 28814 28840
 28841 28842 28858 28864 28872 28885 28892 28907 28910 28926 28930 28934
 28937 28938 28943 28944 28950 28956 28960 28969 28971 28978 28979 28987
 28989 28993 28997 28999 29005 29012 29017 29020 29023 29024 29032 29033
 29037 29042 29049 29052 29063 29078 29080 29087 29091 29102 29106 29115
 29116 29119 29120 29126 29131 29141 29143 29146 29150 29156 29161 29168
 29173 29176 29178 29180 29181 29182 29183 29185 29197 29198 29207 29208
 29216 29225 29232 29236 29237 29239 29245 29246 29257 29258 29262 29266
 29267 29268 29270 29274 29286 29288 29289 29296 29299 29308 29309 29310
 29314 29324 29325 29328 29329 29333 29334 29335 29337 29341 29347 29355
 29360 29362 29364 29366 29368 29372 29376 29378 29380 29381 29383 29385
 29389] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:110: UserWarning: Features [   93   229   230   308   309   384   555   674   895   952   983  1150
  1239  1270  1362  1399  1896  1919  2223  2527  3097  3330  3332  3478
  3881  3895  3987  3990  4035  4103  4154  4155  4488  4677  4859  4865
  4990  5031  5042  5208  5226  5300  5376  5627  5699  5710  5744  6003
  6147  6149  6219  6349  6352  6394  6403  6428  6548  6556  6865  6894
  6955  6964  7141  7311  7325  7386  7509  7520  8075  8106  8138  8174
  8631  8633  8637  9062  9096  9187  9276  9456  9534  9794  9840  9904
  9954 10069 10073 10283 10393 10463 10576 10602 10623 10927 10939 10984
 11010 11193 11551 11707 11716 11930 11934 12542 12649 12946 12992 13273
 13326 13327 13438 13499 13633 13643 13676 13687 13708 14021 14527 14773
 14834 14867 15108 15690 15694 15851 15896 15954 16171 16199 16273 16322
 16454 16514 16559 16597 16936 16995 17161 17281 17292 17495 17925 18127
 18244 18398 18481 18594 18599 18691 18742 18968 19014 19330 19406 19473
 19516 19539 19692 19791 19859 19936 19961 20105 20397 20470 20586 20637
 20648 20680 20689 20717 20746 21009 21176 21546 21568 21609 21866 21933
 22386 22574 22721 22920 23386 23853 23912 23916 23960 23997 24058 24116
 24176 24282 24284 24294 24336 24337 24364 24368 24392 24394 24399 24400
 24409 24418 24422 24455 24504 24513 24518 24547 24578 24603 24606 24626
 24639 24659 24660 24685 24686 24687 24690 24704 24713 24744 24780 24804
 24812 24885 24892 24908 24912 24916 24931 24932 24938 24951 24996 25007
 25030 25042 25044 25047 25051 25068 25070 25083 25086 25088 25100 25107
 25118 25130 25142 25147 25150 25159 25162 25172 25197 25201 25236 25242
 25245 25262 25269 25282 25294 25297 25319 25321 25324 25336 25337 25338
 25343 25362 25367 25371 25377 25389 25397 25427 25438 25441 25461 25467
 25468 25472 25495 25502 25503 25525 25549 25567 25595 25601 25612 25633
 25634 25635 25649 25669 25680 25685 25692 25709 25722 25728 25750 25768
 25772 25773 25775 25786 25806 25808 25819 25821 25823 25833 25841 25846
 25872 25878 25884 25891 25916 25920 25921 25943 25959 25971 25979 26001
 26010 26115 26392 26558 26917 26963 27033 27045 27115 27117 27120 27146
 27169 27171 27173 27183 27187 27190 27195 27203 27212 27221 27222 27228
 27240 27259 27263 27275 27287 27292 27308 27349 27351 27358 27360 27391
 27393 27396 27415 27421 27440 27443 27458 27469 27478 27484 27488 27515
 27517 27530 27540 27547 27548 27550 27591 27599 27617 27637 27638 27642
 27644 27647 27655 27659 27660 27664 27677 27680 27682 27683 27692 27730
 27745 27764 27766 27775 27779 27786 27787 27791 27797 27801 27802 27808
 27818 27821 27827 27831 27832 27844 27845 27847 27851 27863 27868 27869
 27873 27895 27899 27907 27910 27913 27915 27918 27924 27929 27944 27951
 27953 27954 27959 27974 27976 27978 27979 28005 28007 28009 28023 28026
 28028 28029 28032 28036 28068 28089 28090 28093 28099 28102 28112 28115
 28125 28126 28130 28147 28149 28157 28164 28167 28168 28171 28172 28174
 28179 28182 28190 28199 28221 28232 28235 28238 28276 28291 28293 28294
 28300 28309 28311 28316 28317 28319 28321 28329 28370 28373 28388 28391
 28392 28398 28399 28409 28414 28416 28426 28431 28433 28436 28443 28445
 28470 28484 28489 28493 28494 28515 28518 28519 28520 28533 28547 28573
 28595 28603 28627 28631 28632 28650 28655 28662 28668 28689 28713 28751
 28781 28788 28814 28840 28841 28842 28858 28864 28872 28885 28892 28907
 28910 28926 28930 28934 28937 28938 28943 28944 28950 28956 28960 28969
 28971 28978 28979 28987 28989 28993 28997 28999 29005 29012 29017 29020
 29023 29024 29032 29033 29037 29042 29049 29052 29063 29078 29080 29087
 29091 29102 29106 29115 29116 29119 29120 29126 29131 29141 29143 29146
 29150 29156 29161 29168 29173 29176 29178 29180 29181 29182 29183 29185
 29197 29198 29207 29208 29216 29225 29232 29236 29237 29239 29245 29246
 29257 29258 29262 29266 29267 29268 29270 29274 29286 29288 29289 29296
 29299 29308 29309 29310 29314 29324 29325 29328 29329 29333 29334 29335
 29337 29341 29347 29355 29360 29362 29364 29366 29368 29372 29376 29378
 29380 29381 29383 29385 29389] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: RuntimeWarning: invalid value encountered in divide
  f = msb / msw
C:\Users\adeol\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:110: UserWarning: Features [   93   229   230   308   309   384   394   555   674   895   952   983
  1150  1239  1270  1362  1399  1896  1919  2201  2223  2527  3097  3330
  3332  3478  3881  3895  3987  3990  4035  4103  4154  4155  4488  4677
  4865  4990  5031  5042  5208  5226  5298  5300  5376  5627  5699  5710
  5716  5744  6003  6147  6149  6219  6349  6352  6394  6403  6428  6548
  6556  6865  6894  6955  6964  7141  7311  7325  7386  7509  7520  8075
  8106  8138  8174  8631  8633  8637  9062  9096  9187  9276  9456  9534
  9794  9799  9840  9904  9954 10069 10073 10283 10393 10463 10576 10602
 10623 10939 10984 11010 11193 11551 11707 11716 11930 11934 12542 12649
 12946 12992 13273 13326 13327 13438 13499 13633 13643 13676 13687 13708
 14317 14527 14773 14834 14867 14894 15108 15690 15694 15851 15896 15954
 16171 16199 16273 16322 16454 16514 16559 16597 16936 16995 17161 17281
 17292 17495 17925 18127 18244 18398 18481 18594 18599 18742 18968 19014
 19406 19473 19692 19791 19859 19936 19961 20397 20470 20586 20637 20648
 20680 20689 20717 20746 21009 21176 21546 21568 21609 21866 21933 22386
 22574 22721 22920 23386 23853 23912 23916 23960 23997 24058 24111 24116
 24176 24282 24284 24294 24336 24337 24364 24368 24392 24394 24399 24409
 24418 24422 24455 24504 24518 24578 24603 24639 24660 24686 24687 24690
 24704 24741 24744 24780 24812 24892 24931 24932 24938 24941 24951 24996
 25007 25020 25030 25042 25044 25051 25068 25070 25083 25086 25088 25100
 25107 25142 25147 25150 25159 25162 25172 25201 25236 25240 25242 25245
 25269 25282 25294 25297 25319 25321 25324 25325 25327 25336 25337 25338

array([0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.])

In [16]:
# Calculate mean accuracy and look at which samoles were misclassified

print("Mean Accuracy:", scores_full.mean())

misclassified = pd.DataFrame({
    "sample" : x_full.index,
    "true_label" : y_full.values,
    "correct" : scores_full
})

misclassified

Mean Accuracy: 0.6666666666666666

                sample   true_label  correct
0      donor1_lesional     lesional      0.0
1   donor1_nonlesional  nonlesional      0.0
2      donor2_lesional     lesional      1.0
3   donor2_nonlesional  nonlesional      1.0
4      donor3_lesional     lesional      1.0
5   donor3_nonlesional  nonlesional      0.0
6      donor4_lesional     lesional      1.0
7   donor4_nonlesional  nonlesional      1.0
8      donor5_lesional     lesional      0.0
9   donor5_nonlesional  nonlesional      1.0
10     donor6_lesional     lesional      1.0
11  donor6_nonlesional  nonlesional      1.0